version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"

    assignees:
      - "zimavi"

    labels:
      - "dependencies"

    commit-message:
      prefix: "deps"

    open-pull-requests-limit: 5

    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"

    assignees:
      - "zimavi"

    labels:
      - "dependencies"
      - "github-actions"

    commit-message:
      prefix: "ci"

    open-pull-requests-limit: 3

    groups:
      github-actions:
        patterns:
          - "*"