# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# The entry name that will be displayed in the boot menu.
/Yukihana
    # We use the Limine boot protocol.
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/Yukihana.elf

    # loglevel=N where 5 = Critical, 4 = Error, 3 = Warning, 2 = Info, 1 = Debug, 0 = Trace
    cmdline: loglevel=1
